package org.osuosl.ocw;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;


public class Event {
	
    private int event_id;
    private String event_title;
    private Date start_time;
    private Date end_time;
    private String description;
    private String room_title;
    private int track_id;
    private String[] speaker_ids;
    private String presenter;
	
	public Event(){
		this.event_id = -1; //important so as to not be a valid event in the hash map of events
		this.event_title = null;
		this.start_time = null;
		this.end_time = null;
		this.description = null;
		this.event_title = null;
		this.room_title = null;
		this.track_id = -1;
		this.speaker_ids = null;
		this.presenter = null;
	}
	
	public Event(int event_id, String event_title, Date start_time,
  			Date end_time, String description, String room_title, String track_id, String[] speaker_ids,
  			String presenter){
		
		this.event_id = event_id;
		this.event_title = event_title;
		this.description = description;
		this.start_time = start_time;
		this.end_time = end_time;
		this.room_title = room_title;
		this.track_id = Integer.parseInt(track_id);
		this.speaker_ids = speaker_ids;
		this.presenter = presenter;
	}
	
	//Constructor with all parameters as Strings to facilitate when retrieving from the database
	
	public Event(String event_id, String event_title, String start_time,
  			String end_time, String description, String room_title, String track_id, String[] speaker_ids,
  			String presenter){
		
		DateFormat formatter = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzzz yyyy");
		
		this.event_id = Integer.parseInt(event_id);
		this.event_title = event_title;
		this.description = description;
		try{
			this.start_time = formatter.parse(start_time);
			this.end_time = formatter.parse(end_time);
		} catch (ParseException e) {
			e.printStackTrace();
		}
		this.room_title = room_title;
		this.track_id = Integer.parseInt(track_id);
		this.speaker_ids = speaker_ids;
		this.presenter = presenter;
	}
	
	// Getters and Setters auto-generated by eclipse //
	
	public int getEvent_id() {
		return event_id;
	}

	public void setEvent_id(int event_id) {
		this.event_id = event_id;
	}

	public String getEvent_title() {
		return event_title;
	}

	public void setEvent_title(String event_title) {
		this.event_title = event_title;
	}

	public Date getStart_time() {
		return start_time;
	}

	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	public Date getEnd_time() {
		return end_time;
	}

	public void setEnd_time(Date end_time) {
		this.end_time = end_time;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRoom_title() {
		return room_title;
	}

	public void setRoom_title(String room_title) {
		this.room_title = room_title;
	}

	public int getTrack_id() {
		return track_id;
	}

	public void setTrack_id(int track_id) {
		this.track_id = track_id;
	}

	public String[] getSpeaker_ids() {
		return speaker_ids;
	}

	public void setSpeaker_ids(String[] speaker_ids) {
		this.speaker_ids = speaker_ids;
	}

	public String getPresenter() {
		return presenter;
	}

	public void setPresenter(String presenter) {
		this.presenter = presenter;
	}
    


	
}
