package org.osuosl.ocw.BusinessLogic;

import java.util.ArrayList;
import java.util.Iterator;

public class Track {

	private int id;
	private String title;
	private int color;
	private int color_text;
	private ArrayList<Event> events;
	
//	public Track() {
//
//		this.id = -1;
//		this.title = "";
//		this.color = Color.parseColor("#116db6"); //TODO Match color chosen for event list
//		this.color_text = Color.parseColor("white"); //TODO Match color chosen for event list
//	}

	public Track(int track_id, String track_title, int color, int color_text) {

		this.id = track_id;
		this.title = track_title;
		this.color = color;
		this.color_text = color_text;
		
		this.events = new ArrayList<Event>();
	}

	// Getters and Setters auto-generated by eclipse //
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getColor() {
		return color;
	}

	public void setColor(int color) {
		this.color = color;
	}

	public int getColor_text() {
		return color_text;
	}

	public void setColor_text(int color_text) {
		this.color_text = color_text;
	}

	public ArrayList<Event> getEvents() {
		return events;
	}

	public void setEvents(ArrayList<Event> events) {
		this.events = events;
	}

	public void addEvent(Event event) {
		this.events.add(event);
	}
	
	public void removeEvent(Event event) {
		this.events.remove(event);
	}
	
}
